/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/jsonapi": {
    /**
     * Get JSON:API index 
     * @description Get the resource index of JSON:API
     */
    get: operations["getJsonapiIndex"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    JsonApiLink: {
      /** @example https://example.com/link-to-resource */
      href?: string;
    };
    JsonApiMeta: {
      links?: {
        self?: components["schemas"]["JsonApiLink"];
      };
    };
    JsonApiInfo: {
      /** @example 1.0 */
      version?: string;
      meta?: components["schemas"]["JsonApiMeta"];
    };
    JsonApiIndex: {
      jsonapi?: components["schemas"]["JsonApiInfo"];
      /** @example [] */
      data?: (string)[];
      links?: {
        [key: string]: components["schemas"]["JsonApiLink"] | undefined;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  getJsonapiIndex: {
    /**
     * Get JSON:API index 
     * @description Get the resource index of JSON:API
     */
    responses: {
      /** @description The index */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["JsonApiIndex"];
        };
      };
      /** @description JSON:API not activated */
      404: never;
    };
  };
}
